<template>
  <div ref="rootRef" class="export-template-wrapper">
    <!-- Header: Player Info -->
    <div style="margin-bottom: 2rem;">
      <div style="padding: 1.5rem; background: linear-gradient(135deg, rgba(102, 126, 234, 0.15), rgba(239, 68, 68, 0.15)); border-radius: 16px; border: 2px solid rgba(102, 126, 234, 0.3); position: relative;">
        <!-- Decorative corners -->
        <div style="position: absolute; top: 0; left: 0; width: 30px; height: 30px; border-top: 3px solid #667eea; border-left: 3px solid #667eea; border-radius: 16px 0 0 0;"></div>
        <div style="position: absolute; top: 0; right: 0; width: 30px; height: 30px; border-top: 3px solid #ef4444; border-right: 3px solid #ef4444; border-radius: 0 16px 0 0;"></div>
        <div style="position: absolute; bottom: 0; left: 0; width: 30px; height: 30px; border-bottom: 3px solid #ef4444; border-left: 3px solid #ef4444; border-radius: 0 0 0 16px;"></div>
        <div style="position: absolute; bottom: 0; right: 0; width: 30px; height: 30px; border-bottom: 3px solid #667eea; border-right: 3px solid #667eea; border-radius: 0 0 16px 0;"></div>
        
        <!-- Player Info -->
        <div style="display: flex; align-items: center; gap: 1rem;">
          <img 
            :src="playerAvatar" 
            alt="Player Avatar"
            style="width: 70px; height: 70px; border-radius: 50%; border: 3px solid #667eea; box-shadow: 0 0 20px rgba(102, 126, 234, 0.5);"
          />
          <div>
            <div style="color: #a0aec0; font-size: 0.9rem; font-weight: 500; margin-bottom: 0.25rem;">
              {{ $t('export.defendantPlayer') }}
            </div>
            <div style="color: #fbbf24; font-size: 1.3rem; font-weight: 700; text-shadow: 0 0 10px rgba(251, 191, 36, 0.4);">
              {{ playerName }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 主内容：左右分栏 -->
    <div style="display: grid; grid-template-columns: 500px 1fr; gap: 2rem; margin-bottom: 1.5rem;">
      <!-- 左侧列 -->
      <div style="display: flex; flex-direction: column; gap: 1.5rem;">
        <!-- 游戏人格称号 -->
        <div v-if="personalityTitle" style="position: relative;">
          <div style="position: absolute; top: -8px; left: -8px; width: 16px; height: 16px; background: linear-gradient(135deg, #667eea, #764ba2); border-radius: 50%; box-shadow: 0 0 15px rgba(102, 126, 234, 0.6);"></div>
          <PersonalityTitle :title="personalityTitle" />
        </div>

        <!-- 受害者档案 -->
        <div style="position: relative;">
          <div style="position: absolute; top: -8px; left: -8px; width: 16px; height: 16px; background: linear-gradient(135deg, #ef4444, #dc2626); border-radius: 50%; box-shadow: 0 0 15px rgba(239, 68, 68, 0.6);"></div>
          <VictimProfile 
            :playerName="playerName"
            :totalGames="totalGames"
            :totalHours="totalHours"
          />
        </div>

        <!-- 雷达图 -->
        <div v-if="radarDimensions.length === 6" style="position: relative; padding: 1rem; background: rgba(102, 126, 234, 0.05); border-radius: 12px; border: 1px solid rgba(102, 126, 234, 0.2);">
          <div style="position: absolute; top: -8px; left: -8px; width: 16px; height: 16px; background: linear-gradient(135deg, #fbbf24, #f59e0b); border-radius: 50%; box-shadow: 0 0 15px rgba(251, 191, 36, 0.6);"></div>
          <RadarChart :dimensions="radarDimensions" :size="450" />
        </div>
      </div>

      <!-- 右侧列：罪名清单 -->
      <div style="position: relative;">
        <div style="position: absolute; top: -8px; right: -8px; width: 20px; height: 20px; background: linear-gradient(135deg, #ef4444, #dc2626); border-radius: 50%; box-shadow: 0 0 20px rgba(239, 68, 68, 0.8); z-index: 10;"></div>
        <ExportRoastAnalysis :charges="roastCharges" />
      </div>
    </div>

    <!-- Footer -->
    <div style="margin-top: 1.5rem; padding: 0.875rem 1.5rem; background: linear-gradient(135deg, rgba(239, 68, 68, 0.15), rgba(251, 191, 36, 0.15)); border-radius: 12px; border: 2px solid rgba(251, 191, 36, 0.3);">
      <div style="display: flex; justify-content: center; align-items: center; gap: 0.75rem;">
        <span style="color: #a0aec0; font-size: 0.95rem; font-weight: 500;">Generated by</span>
        <span style="color: #fbbf24; font-size: 1.1rem; font-weight: 800; letter-spacing: 1px; text-shadow: 0 0 15px rgba(251, 191, 36, 0.4);">RATEMYSTEAM.COLAB.DUKE.EDU/span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import PersonalityTitle from './PersonalityTitle.vue'
import VictimProfile from './VictimProfile.vue'
import RadarChart from './RadarChart.vue'
import ExportRoastAnalysis from './ExportRoastAnalysis.vue'

interface RadarDimension {
  name: string
  value: number
  description?: string
}

interface ChargeItem {
  charge: string
  comment: string
}

interface Props {
  playerName: string
  playerAvatar: string
  totalGames: number
  totalHours: number
  personalityTitle?: string
  radarDimensions: RadarDimension[]
  roastCharges: ChargeItem[]
}

defineProps<Props>()

// Expose root element ref for html2canvas
const rootRef = ref<HTMLElement>()
defineExpose({ rootRef })
</script>

<style scoped>
.export-template-wrapper {
  background: linear-gradient(135deg, #0a0e27 0%, #1a1f3a 100%);
  padding: 2rem;
  width: 1400px;
  min-height: 1900px;
  user-select: none;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
}
</style>
